principal_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

# Login #

login:
    path:     /login
    defaults: { _controller: AppBundle:usuarios:login }

login_check:
    path:     /login_check

validacion_login:
    path:     /validacion_login
    defaults: { _controller: AppBundle:usuarios:validacion_login }

# Dashboard # 

dashboard:
    path:     /dashboard
    defaults: {_controller: AppBundle:usuarios:dashboard }

# Logout #

logout:
    path:     /logout

# Grupos #

leer_archivo_txt:
    path:     /leer_archivo_txt 
    defaults: { _controller: AppBundle:grupos:leer_archivo_txt }

grupos:
    path:     /grupos 
    defaults: { _controller: AppBundle:grupos:grupos }

ver_ip:
    path:     /ver_ip
    defaults: { _controller: AppBundle:grupos:ver_ip }

# Usuarios #

lista_usuarios:
    path:     /lista_usuarios 
    defaults: { _controller: AppBundle:usuarios:lista_usuarios }

registro_usuario_grupo:
    path:     /registro_usuario_grupo
    defaults: { _controller: AppBundle:usuarios:registro_usuario_grupo }

registro_super_usuario:
    path:     /registro_super_usuario
    defaults: { _controller: AppBundle:usuarios:registro_super_usuario }

actualizar_estado:
    path:     /actualizar_estado/{email}  
    defaults: { _controller: AppBundle:usuarios:actualizar_estado }

editar_usuario:
    path:     /editar_usuario/{id}
    defaults: { _controller: AppBundle:usuarios:editar_usuario }

eliminar_usuario:
    path:     /eliminar_usuario/{id}
    defaults: { _controller: AppBundle:usuarios:eliminar_usuario }

# Target #

grupos_target:
    path:     /grupos_target 
    defaults: { _controller: AppBundle:target:grupos_target }

registro_target:
    path:     /registro_target
    defaults: { _controller: AppBundle:target:registro_target }

lista_target:
    path:     /lista_target 
    defaults: { _controller: AppBundle:target:lista_target }

editar_target:
    path:     /editar_target
    defaults: { _controller: AppBundle:target:editar_target }

eliminar_target:
    path:     /eliminar_target
    defaults: { _controller: AppBundle:target:eliminar_target }

# Acl #

grupos_acl:
    path:     /grupos_acl 
    defaults: { _controller: AppBundle:acl:grupos_acl }

registro_acl:
    path:     /registro_acl
    defaults: { _controller: AppBundle:acl:registro_acl }

lista_acl:
    path:     /lista_acl 
    defaults: { _controller: AppBundle:acl:lista_acl }

editar_acl:
    path:     /editar_acl
    defaults: { _controller: AppBundle:acl:editar_acl }

eliminar_acl:
    path:     /eliminar_acl
    defaults: { _controller: AppBundle:acl:eliminar_acl }

# Aliases #

grupos_aliases:
    path:     /grupos_aliases 
    defaults: { _controller: AppBundle:aliases:grupos_aliases }

registro_aliases:
    path:     /registro_aliases
    defaults: { _controller: AppBundle:aliases:registro_aliases }

lista_aliases:
    path:     /lista_aliases 
    defaults: { _controller: AppBundle:aliases:lista_aliases }

editar_aliases:
    path:     /editar_aliases
    defaults: { _controller: AppBundle:aliases:editar_aliases }

eliminar_aliases:
    path:     /eliminar_aliases
    defaults: { _controller: AppBundle:aliases:eliminar_aliases }